version: '3.9'
services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - type: bind
        source: ./postgres
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'on-failure'
    volumes:
      - type: bind
        source: ./.env.docker
        target: /app/.env
    depends_on:
      - postgres
    ports:
      - 3001:3001